OperationCode/resources_api

db_setup/app/__init__.py
db_setup/app/models.py
db_setup/profile.py
db_setup/resources.yml

There are still some optimizations to be done, but I'm starting this PR with something that works. We can continue to optimize before we actually merge it if you feel like that's necessary

Create a resource if it doesn't exist, update a resource if it does

---

README.md

Following these instructions doesn't currently work... Need to figure out some things about `import_resources()` and alembic not playing nice. Starting this PR so @wimo7083 can take a look at it with me.

Include local setup instructions in README.md

---

README.md
db_setup/app/__init__.py

Make import_resources() a click command

---

app/api/routes.py
configs.py

This adds an endpoint that allows you to get a specific resource by id. This resolves one of the issues in #14

Add an endpoint for getting a specific resource

---

.env
.gitignore
.travis.yml
Pipfile
Pipfile.lock
requirements.txt
tests/conftest.py
tests/unit/test_routes.py

Default .env file
Started add pipfile
Simple tests.
To run you need to install[ `pipenv`](https://realpython.com/pipenv-guide/)
This will load any variables in `.env`
`pipenv shell` will load a python shell scoped to the change. Make sure you are in the flask_app directory.
Then do `pytest`
```powershell
C:\Users\wimo7\Desktop\resources_api [initial_tests +0 ~0 -2 | +2 ~2 -0 !]> pytest
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-3.9.2, py-1.7.0, pluggy-0.8.0
rootdir: C:\Users\wimo7\Desktop\resources_api, inifile:
collected 1 item
tests\unit\test_routes.py .                                              [100%]
========================== 1 passed in 0.16 seconds ===========================
```

initial tests

---

.travis.yml
Pipfile.lock

Travis was failing for every PR based on a dependency issue. This fixes that problem.

Fix the dependency issues causing travis failure

---

app/api/__init__.py
app/api/routes.py

Added code for a new endpoint that is designed to update a resource based on the id passed in and any optional JSON form data parameters given in a PUT request. Uses helper function to update resource with parameters from the request. Closes #34.

Added endpoint for updating a resource

---

README.md

#58 
I believe i have done this correctly this time. This PR adds the Linux setup instructions to the readme and adds the toggleable boxes for the different OS instructions.

Add linux setup instructions to readme

---

resources.yml

Add a bunch of resources to the resources.yml file

Add a bunch of resources

---

app/api/routes.py
configs.py

This returns an empty array to the browser.

add /GET category route

---

app/__init__.py
app/api/errors.py
app/api/routes.py
app/errors/__init__.py
app/errors/handlers.py

Fixes #5 (at least I think it does).
I need a really good code review because I don't know if I put everything in the right place. It does work, but I don't know if it's good code.
Also, sorry about the fact that there's so much more to the diff due to indentation change only. The purpose of that was to remove all of the `except` blocks because the new `teardown_request` handles the exceptions now.
@heavysaturn Would you please take a look at this too? I can't officially request a review from you, not sure why.

Teardown requests

---

.env
README.md

Fixes #55 with a documentation note.

Add documentation note about .env

---

app/__init__.py
app/api/routes.py
app/errors/handlers.py
app/models.py
app/utils.py

Addresses one of the points in #25.
This adds helpful information to each response, such as API version and status. Willing to have a conversation about what other information might be helpful for all requests.

Return routes with more information about the request

---

resources.yml

Additional nodes to the resources.yml file.

Added Resources from aaron-s and Slack

---

.env
app/api/routes.py
app/models.py
app/utils.py
tests/conftest.py
tests/unit/test_routes.py

Timestamps

---

.codeclimate.yml

Created codeclimate.yml file to ignore "migrations" folder from Code Climate checks.

Add .yml file to ignore specified folders and files

---

resources.yml

Add a bunch of resources. Remove some duplicates. Update some to use HTTPS instead of HTTP.

Add resources

---

app/api/routes.py
tests/unit/test_persistent_routes.py
tests/unit/test_routes.py

-  Added routes for making `PUT` requests to 
`api/v1/resources/<id>/upvote` and 
`api/v1/resources/<id>/downvote` 
as per #75 
and confirmed working functionality via Postman.
-  Attempted to write a test for this however was unable to get pytest to run due to the following error:
```console
$ cd resources_api/tests/unit && pytest ./test_routes.py
ImportError while loading conftest '/home/skyelah/Desktop/Coding/learning/learning-python/resources_api/tests/conftest.py'.
../conftest.py:2: in <module>
from app import create_app, db as _db
../../app/__init__.py:3: in <module>
from configs import Config
../../configs.py:20: in <module>
raise KeyError("Application requires 'SQLALCHEMY_DATABASE_URI' to run in non DEVELOPMENT")
E   KeyError: "Application requires 'SQLALCHEMY_DATABASE_URI' to run …
```

Vote routes

---

README.md

Adds a little note about the history of the project to the bottom of README.md

Add history to README

---

app/cli.py
requirements.txt

Update pyyaml requirements to 4.2b1 or newer

---

app/errors/handlers.py
app/utils.py

Added handler for 405 in app/error/handlers.py and added 405 in err_map

Issue #112 method not allowed

---

app/errors/handlers.py
tests/unit/test_routes.py

Add handler for 400 bad request

---

app/api/routes.py
app/cli.py
app/utils.py
tests/unit/test_routes.py

Addresses #79 
Increased code coverage by excluding import resources as it isn't needed in
production.
Removed blocks catching NoResultsFound on get() queries.

Improve test coverage

---

.env

Fixes a bug preventing make setup from running.

Fix make setup bug

---

.travis.yml

This removes the API key for code climate from the .travis.yml file and replaces it with the secure, encrypted version of the new API key.

Cycle Code Climate API key

---

Makefile

Removes code that caused the docker container to disconnect from host I/O

Fixes make all

---

Dockerfile
Makefile
app.ini
app/__init__.py
app/api/routes.py
app/healthcheck.py
requirements.txt
run.py

Fixes #136 
Adds some basic instrumentation to the Resources API. We should iterate on this, because I really don't know what I'm doing.

Add instrumentation

---

.env
Makefile
app/__init__.py
app/api/routes.py
app/cli.py
app/models.py
app/utils.py
configs.py
requirements.txt

Includes all changes from PR #150

Add search endpoint

---

app/api/routes.py
app/utils.py

This commit has search results displayed directly from algolia
without querying the database first.
Closes #173

Optimize search results

---

app/api/routes.py
app/cli.py
app/utils.py
requirements.txt
tests/conftest.py
tests/unit/test_routes.py

Added testing for the search endpoint

---

openapi.yaml
requirements.txt

@wimo7083 @aaron-suarez 
Created an OpenAPI 3.0 yaml file using Swagger. It still needs work.

#184 - Documentation - Complete

---

app/api/routes.py
tests/unit/test_routes.py

* Created happy and sad path tests for GET /categories/{id} endpoint
* Created API endpoint for GET /categories/{id}
* Created get_category(id) method
* New feature (non-breaking change which adds functionality)
Closes Issue #198

Created GET /categories/{id} Route 

---

app/static/openapi.yaml

Copied 422 and 401 responses from Create Resource and added to Update Resource
Fixes #205

Added 401, 422 to 'Update Resource' endpoint documentation

---

CONTRIBUTING.md

Added Docker and Docker Compose install and usage instructions. Also, formatted the markdown document.
resolves #201

docs: add CONTRIBUTING with Docker help

---

requirements.txt
tests/unit/test_routes.py

First round of negative tests

---

app/api/__init__.py
app/api/routes.py
requirements.txt

Fixes #250  
- Added a new package to enable CORS
- API routes accept requests from allowed origins(e.g. localhost:3000, operationcode.org, etc. )

Fix CORS issue

---

Makefile
app/cli.py

Fixes #83
Please let me know your thoughts as this is the first iteration.

created click command for checking expired url

---

app/api/routes/helpers.py
app/api/routes/resource_creation.py
app/api/routes/resource_modification.py
tests/unit/test_routes/test_resource_create.py
tests/unit/test_routes/test_resource_update.py

Added method to ensure bool and allow strings that parse to bool

---

Makefile

added run_windows target to run the API on Windows.

Makefile support for Windows

---

Ops.md

This actually fixes #187, we don't need to do a click command since this process works. Thanks for your help @irvingpop! Please merge if you think the steps and explanation look good 😄

Add instructions for manual DB backups

---

configs.py

Increased max page size to 200. Fixes #334

increased max page to 200

---

app/api/routes/categories.py
app/api/routes/languages.py
app/static/openapi.yaml
app/utils.py
resources.yml
tests/conftest.py
tests/unit/test_routes/test_categories.py
tests/unit/test_routes/test_languages.py
tests/unit/test_routes/test_utils.py

removed pagination for GET languages and GET categories

---

app/api/routes/resource_retrieval.py
app/api/routes/search.py
app/utils.py
tests/unit/test_routes/test_searching.py

Fixes https://github.com/OperationCode/front-end/issues/1160

Ensure the search pagination details are included in response

---

.circleci/config.yml

When a new PR is merged into `main`, I would like to merge that to the staging environment automatically, so we can test right away.

CircleCI: automatically deploy main branch to staging on every merge

---

README.md

Resources page is now live and should be clickable in the readme

make resources link clickable

---

Makefile

Added 'make shell' command to Makefile, using 'docker-compose run resources-api flask shell'.

Added 'make shell' command to Makefile

---

app/api/routes/resource_modification.py
tests/unit/test_routes/helpers.py
tests/unit/test_routes/test_resource_update.py

This should hopefully account for that case. Let me know if there is anything missing or irrelevant!

Specified languages modification null checking

---

app/__init__.py

Fixes an issue with rate limiting

Add ProxyFix to rate limiting

---

app/__init__.py

Fix problem with ProxyFix

---

app/__init__.py

Fix ProxyApp implementation

---

app/__init__.py

Fix ProxyFix implementation

---

app/static/openapi.yaml

- Change snake case names to PascalCase
- Change a few variable names to be more clear on what they are
closes #259

Open api Structure Names
