db_setup/app/__init__.py
db_setup/app/models.py

This adds a route for getting all resources.
Issues:
- I don't know whether putting the route in `__init__.py` is the right choice.
- There's no pagination so it takes a very long time to return results
- I'm not sure what the significance of `@property` is for the `serialize()` method, but that's what the example on StackOverflow used... so if that doesn't need to be a property, we can change that I'm sure

Add GET /resources endpoint

---

README.md
app/cli.py

Turns out that `db.create_all()` was the missing line we needed to create the tables in a fresh db. It can now be ran using `flask db_migrate create_tables`.
Also, when you run `flask db_migrate init`, the db needs to be passed into the `create_resource()` function, this PR also fixes that too.

Add create_tables click command for easier setup of local db

---

app/api/routes.py
app/models.py
app/utils.py
configs.py

Fixes #15 
Pagination is implemented using Flask-SQLAlchemy's built-in paginator. The specific page is requested using a query param called `page`. The request looks like this:
```
GET api/v1/resources?page=1
```
The number of resources per page is included in the Config class, so we can easily change it later. I imagine that eventually we will add a `CATEGORIES_PER_PAGE` and `LANGUAGES_PER_PAGE` as well, for the `GET api/v1/categories` and `GET api/v1/languages` routes.

Add pagination for the get_resources route

---

app/api/routes.py

Modified the formatting of the implementation for pagination of /languages route (preexisting code) to match the format of the pagination implementation for /resources route. Closes #32.

Fixed formatting to match pagination implementation for resources

---

app/api/__init__.py
app/api/routes.py
app/utils.py

Opening a new pull request because the other one fell victim to the GitHub problems that have been happening today and yesterday.
This PR solves #29, allowing you to filter GET requests to the resources endpoint by language, category, or both. The requests are still paginated in the same way, with the filtering being applied _before_ the pagination is done. All filters are caps insensitive.

Params for filtering resources on language or category. 

---

app/api/routes.py

Refactored the implementation for pagination of /languages route to match that of the /resources route due to changes in paginator interface. Updated code passes in query to `language_paginator.items` and removes `Language` argument from Paginator constructor. Closes #32.

Modified implementation of getting languages route

---

app/cli.py

There was a byte (0x9d) in resources.yml that broke my import on my Windows VM. Not sure if this was recently added when I added all the new resources or what. The first google search says this should fix it.

Fix encoding in import_resources

---

app/api/routes.py

This fixes a bug where if you tried to set "paid" to `false` or "notes" to `""` or `null`, it would not update the resource.

Fix bug in PUT /resources

---

README.md

I updated the installation instructions that resolves a couple of issues:
1. Added instructions to change the pg_hba.conf file to modify the method column in order to allow users created in postgresql on linux to run createdb command.
2. Added instructions and the command to run if virtualenv is being created using python2.7 instead of the required python3.7.

Providing an update to the installation instructions

---

.env
app/api/routes.py
app/models.py
app/utils.py
pytest.ini
tests/conftest.py
tests/unit/test_routes.py

This addresses #66.
I am thinking we'll probably need to add a parameter to the `GET /resources` route so that the front end can actually query for resources based on the `created_at` or `last_updated` data. Let me know if you want to see that as part of this PR. 
I'm willing to have a discussion about whether we should include these timestamps in the data returned by all requests (I wasn't sure so I decided to not include it until we can have a discussion about it).

Add create and update timestamps to Resource objects

---

.travis.yml
Pipfile
Pipfile.lock

Per conversations in Slack, we're going to try to add CodeClimate instead of Coveralls.

Add code climate to repo

---

.travis.yml
Makefile
app/__init__.py
app/api/routes.py
app/health_check.py
tests/conftest.py
tests/unit/test_handlers.py
tests/unit/test_models.py
tests/unit/test_routes.py

There is no test coverage asserting the JSON returned from a 500 error, so I wanted to go ahead and add that. Current implementation fails the tests rather than allowing the API to return a 500. Hopefully we can figure out how to "raise an error" without letting it bubble all the way up to the test suite.
I went ahead and tried to increase test coverage in all the ways I know how. It's now up to 88%. Suggestions about how exactly to increase test coverage in the remaining 12% would be appreciated, but I'm not sure how to test the CLI or the error handlers (as a matter of fact, I'm not entirely convinced the handlers even work, so any thoughts surrounding that are appreciated).

Add test coverage

---

app/__init__.py

I've gotten caught up by this so many times that I'm rather annoyed by it. I fully understand the reasons for having strict slashes, but I think that from a usability perspective, I'd rather the API not return a 404 just because someone put in a slash at the end.

Disable strict slashes

---

app/api/routes.py

Issue #126: remove MultipleResultsFound condition check from routes.
Getting multiple results from resources is impossible is because results are queried by `id` and `id` is a unique identifier. Therefore, the check for `MultipleResultsFound` is not necessary.
see https://github.com/OperationCode/resources_api/pull/125#discussion_r272812093 for more details

Issue #126: remove MultipleResultsFound condition check from routes

---

app/api/routes.py

This removes a lingering `MultipleResultsFound` that was supposed to have been removed in #127

Remove MultipleResultsFound that was somehow left in there

---

app/api/routes.py
tests/unit/test_routes.py

I was getting a 500 error when I would do `GET http://127.0.0.1:8000/api/v1/resources/9999`. This fixed that to make it a 404 instead.

Fix the redirect when resource is not found

---

app/api/routes.py
app/models.py
tests/unit/test_routes.py

Fixes #130 
This filter works for me locally, but for some reason when the query occurs in the tests it returns no resources and then the response redirects to `404` (which would be correct if there were no resources). I'm confused why this is happening since I'm pretty sure it's the same seed data in `module_db` as in my local db. Help fixing the test would be greatly appreciated!

Add filter for paid/free resources

---

app/api/routes.py
tests/unit/test_routes.py

Fixes #113 
Now, if you're missing a required parameter (currently, `name`, `url`, and `category`), you will get a response similar to the following:
```json
{
"apiVersion": "1.0",
"data": null,
"errors": {
"missing_params": [
"name",
"url",
"category"
],
"type": "validation"
},
"status": "Unprocessable Entity",
"status_code": 422
}
```

Add basic validation to create resource endpoint

---

app/api/routes.py

When creating a free resource, `paid` is `False`. This means that you would always get a validation error. This change checks for `None` explicitly, allowing values of `False` to still be considered valid (as they should be).

Fix bug when creating a Free resource

---

.gitignore
.travis.yml
bin/build
bin/publish
bin/run.sh
lib/util.sh

This allows our CI to automatically build a docker image and publish it to dockerhub when something is committed to either `staging` or `master`. Fixes #139

Add scripts to build and publish docker image

---

.env
Makefile
docker-compose.yml

This changes the name of the Postgres host to `resources-postgres` to more closely resemble production. See https://github.com/OperationCode/operationcode_infra for the prod configuration

Change POSTGRES_HOST to resources-postgres

---

requirements.txt

Thanks for the opportunity to learn/read about pinning dependencies! 
Pyyaml's current stable version is 5.1. Not sure if we needed/wanted to move to that one yet.

Pinning pyyaml dependency

---

Dockerfile
Makefile
README.md
configs.py
docker-compose.yml

For some strange reason when we switched to Docker, we started using port 8000. I'm not really sure why that was the case, but now in prod we're using the default port when we run flask. I think it's a good idea for local environments to more closely resemble prod, so I made the change in the Dockerfile and elsewhere to use the default port.

Use port 5000 instead of 8000

---

Makefile

There are two issues with the Makefile that have been annoying me and @Digbigpig, so I fixed them.
1) Occasionally there are orphan containers when you try to do `make minty-fresh` and the command fails rather than successfully removing the orphan containers. This will make it truly minty-fresh.
2) After a recent change to the `CMD` in the Dockerfile, `make fresh-restart` fails because the container is already running. This takes down the container that's created by the Dockerfile CMD and brings it back up for you automagically.
This shouldn't negatively affect any situations where these problems are not present.

Fix issues with the Makefile

---

.bandit
.travis.yml
Makefile
requirements.txt

Fixes #153 
This adds bandit into the CI pipeline. I went ahead and excluded `/tests` because there were a bunch of issues but I don't think that matters. Because I wanted to exclude `/tests`, I had to specify bandit 1.5.1. We will need to upgrade past 1.6.0 once this is resolved https://github.com/PyCQA/bandit/issues/488 or we won't be able to exclude the tests directory.

Add security checks

---

app/api/auth.py
app/api/routes.py
app/utils.py

To facilitate ingesting of a single log stream, we should just log everything to stdout.

Log to stdout instead of log files

---

Makefile
configs.py
run.py

While looking into #99 I realized that there are some files such as `run.py` and `configs.py` that exist outside the `app` directory but are still critical to the application. These files were not being checked by `make lint`. Now they will be.
This fixes linting errors in those files, as well as changing the Makefile to include them in all future runs of `make lint`.

Fix linting errors in root directory

---

app/api/auth.py

The new backend gets rid of the `user` dict and just sends the email and password directly. It's also to `/auth/login` rather than `api/v1/sessions`.

Fix auth to be compatible with new backend

---

app/api/routes.py
tests/unit/test_routes.py

Followed same pattern as get_category route to set up the get_language route and added tests for getting a single language by ID and testing for out of bounds languages.
Tested retrieving a single language on Postman successfully.

Adding get_language route and tests

---

app/api/routes.py
app/static/openapi.yaml
tests/unit/test_routes.py

Hello!
Refers Issue [#194 ](https://github.com/OperationCode/resources_api/issues/194)
I have added 'paid' attribute filtering to the search endpoint using algolia filters, due to not having API key I haven't been able to test it thoroughly.
Possible issue I noticed ( unrelated to this PR ) is that the algolia query API search has a limit of 512 characters where if the user typed a really long query, it would return a 500 error
Let me know if there is anything else I can do, this is my first time 😅

Added 'paid' algolia filtering to search endpoint

---

app/models.py

- Removes 4 CodeClimate warnings about having many returns, and 1 warning about having high cyclomatic complexity, while preserving the same behavior. This was motivated by #82 .
- Uses a generator so that the test will short-circuit if any of the earlier checks fail.
- See https://codeclimate.com/github/OperationCode/resources_api/app/models.py/source#issue-a49e24d316f36fbe89761497d99f0928 for the warnings of interest.
<a href="https://cl.ly/211ddc5c095e" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/3A262b0D2p3q0Z3Z0L1n/Image%202019-10-05%20at%208.31.38%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

[refactor] Reduce cognitive complexity from multiple return statements

---

app/static/openapi.yaml

@kylemh pointed out that we have a problem in production with the examples not rendering properly. I have not figured out a root cause, but I suspect a change was made to the library we're using to render the docs. In any case, I fixed it now per [the spec](https://swagger.io/docs/specification/adding-examples/).
Before:
After:

Update examples from inline JSON to YAML

---

app/api/routes.py
app/static/openapi.yaml
tests/unit/test_routes.py

Refers [Issue#194](https://github.com/OperationCode/resources_api/issues/194)
Added Language & category filtering to search endpoint with tests & docs.
Please let me know if there is anything that is needed
Edit:
Tests will fail currently because need actual API Key to be able to set_settings correctly for the attributes that need faceting for algolia, otherwise they should work fine. any thoughts? 
Possible solution:
Add the attributes throught the [dashboard](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-arrays/#using-the-dashboard) and remove the set_settings part from the endpoint, that should make the tests work correctly without having to use the API key

Added Language & Category filtering to search endpoint

---

app/static/openapi.yaml

The Update Resource endpoint used the incorrect `Request Body Schema`. This updates it to the correct schema.
Before:
After:

Fix Update Resource schema

---

app/api/routes.py
app/static/openapi.yaml
tests/unit/test_routes.py

#234 Allows you to filter the search endpoint by multiple languages. This PR is to maintain consistency with both endpoints, but also because it's a useful feature in its own right. It should be noted that Algolia will display results for anything kind of close to either language passed in, whereas the List Resources endpoint makes it a hard secondary filter. So if you try to list Resources for both `Scala` and `Python` for example and there are none that have both of those, it will return no results.

Filter by multiple languages on List Resources endpoint

---

app/api/routes.py
tests/unit/test_routes.py

Upon further testing (Thanks to chynh!), it appears `request.args.getlist` returns an empty list ( instead of `None` as I originally thought, my bad! ) which lead to `if ininstance(languages,list):` always being true which triggered an AlgoliaException due to filtering being invalid ( `filtering: ()` <- due to languages appending nothing)
Likewise for the `category` filtering; it appends an empty string (i.e: given `/search?category`) which leads to filtering error due to incorrect format
This should hopefully fix that issue.
See #234 for previous implementation and details
See [Filters](https://www.algolia.com/doc/api-reference/api-parameters/filters/) for how algolia filters

Fix for search endpoint filtering

---

app/api/routes.py
app/api/validations.py
app/static/openapi.yaml
tests/conftest.py
tests/unit/test_routes.py

Fixes #206 
**EDIT:** The below examples in this description will be updated as I make changes to the interface, so assume that it is accurate and correct based on the latest commit. 
**EDIT 2:** There is an additional breaking change where when Algolia fails, it will now say in the response that the error has to do with Algolia. Now if Algolia fails, the request fails altogether so we always stay in sync. In addition, `PUT /resource/<id>` and `POST /resources` work without needing algolia as long as you're in the development environment.
This PR allows you to send a list of resources to the `POST /resources` endpoint to add all of them at once. If any resource in the list fails validation, none should be created until the issues are fixed, allowing for subsequent similar requests but …

Add support for creating multiple resources to POST /resources endpoint

---

tests/unit/test_routes.py

Closes #207 
So beyond checking the status code. I could look into finding a way to create a assertion comparing the static/openapi.yaml file against the downloaded yaml file. I guess i would have to look into how to access the downloaded yaml file without using a hardcoded path in a context manager? What do you think?

add basic status code tests for views

---

migrations/env.py

If there is a `%` in the db string, it throws an error. See https://stackoverflow.com/a/46807249

Escape the DB uri

---

Dockerfile
app.ini

This started due to looking at the production logs and getting overwhelmed with logs of `/healthz` over and over again. Upon further research, I found this article https://www.techatbloomberg.com/blog/configuring-uwsgi-production-deployment/
I decided to go ahead and add all of the sections I think were relevant to us right now, and we'll try it out and see what happens.

Update the uwsgi settings with better production features

---

app/api/routes/api_key.py
app/api/routes/categories.py
app/api/routes/languages.py
app/api/routes/resource_creation.py
app/api/routes/resource_modification.py
app/api/routes/resource_retrieval.py
app/api/routes/search.py
app/static/openapi.yaml
app/utils.py
tests/unit/test_routes/helpers.py
tests/unit/test_routes/test_api_key.py
tests/unit/test_routes/test_categories.py
tests/unit/test_routes/test_invalid_put_post.py
tests/unit/test_routes/test_languages.py
tests/unit/test_routes/test_resource_create.py
tests/unit/test_routes/test_resource_retreival.py
tests/unit/test_routes/test_resource_update.py
tests/unit/test_routes/test_searching.py
tests/unit/test_routes/test_utils.py

Per @kylemh and @manthonyg, the front end code is [getting unwieldy](https://github.com/OperationCode/front-end/pull/1100#discussion_r422439722). This changes the `data` attribute to be called the actual description of the data.
This is a pretty big breaking change, but I'm choosing not to increment the API version because there are currently no production clients that are depending on the API in its current state. If there is anything up at https://operationcode.org/resources currently, it's almost certain that no one is actually using it, so if it breaks that's ok.
Changelist:
- Call the data returned from the "API Key Request" endpoint `credentials`
- Call the data returned from "Search", "List Resources", and "Create Resources" endpoints `resources`
- Call the data returned from the …

Specify the datatype instead of just calling everything "data"

---

app/api/__init__.py

Since Zeit has rebranded `now.sh` as `vercel.app`, we're seeing CORS issues on https://operation-code-git-update-deps.operation-code.vercel.app/resources/1
This should fix that issue.

Add vercel.app to CORS allowed origins

---

app/api/routes/resource_retrieval.py
tests/unit/test_routes/test_utils.py

fixes #338

---

tests/conftest.py

When we merged #341, the tests started failing on this line
https://github.com/OperationCode/resources_api/blob/b4d281c2d8215162309a2db3f66d20d13fe8716b/app/api/routes/resource_retrieval.py#L91
I'm not sure exactly why this fixes it, but it's more correct anyway and it happens to fix the tests. I'm going to merge it and then do some manual testing on staging and make sure everything is good to go before we deploy to prod.

Raise DBAPIError rather than None

---

.circleci/config.yml

The problem here: https://app.circleci.com/pipelines/github/OperationCode/resources_api/524/workflows/39d5b471-abef-4067-b6a1-50d021043875/jobs/648
was that using CIRCLE_BUILD_NUM is unreliable because each workflow job will have a new number.   This PR proposes using the git commit sha as the tag instead, which is more reliable and traceable back to git!
Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

Use CIRCLE_SHA1 as the image tag instead of BUILD_NUM which is unreliable

---

app/api/routes/resource_modification.py

Fixes #356 
example PUT to api/v1/resources/1:
```json
{
"notes": "test2"
}
```
old logs: 
```
2020-08-13 02:54:24,753 INFO User: ekmendes1@gmail.com Route: /api/v1/resources/1 Payload: {'notes': 'test2'}
2020-08-13 02:54:24,788 INFO Updating resource. Old data: {'id': 1, 'name': 'Free Programming Books', 'url': 'https://github.com/vhf/free-programming-books', 'category': 'Books', 'languages': ['multiple'], 'paid': False, 'notes': 'test1', 'upvotes': 0, 'downvotes': 0, 'times_clicked': 0, 'created_at': '2020-08-02 03:04:21', 'last_updated': '2020-08-13 02:49:18'}
```
new logs:
```
2020-08-13 02:49:18,768 INFO User: ekmendes1@gmail.com Route: /api/v1/resources/1 Payload: {'notes': 'test1'}
2020-08-13 02:49:18,816 INFO Updating resource. Old data: {"id": 1, "name": "Free Programming Books", …
```

Wrapped resource.serialize with json.dumps() to convert object to json

---

app/utils.py

I didn't open a new issue because it didn't seem necessary, but #388 is blocked by the log directory creation.
I've gone though the code, checked where it was created and removed the related lines.

Remove log directory creation

---

app/api/routes/resource_modification.py
tests/unit/test_routes/test_resource_update.py

We discovered an auth error in OperationCode/front-end#1283 where the API doesn't know how to handle an upvote or downvote without an API key sent in the header. This should fix that issue.

Support authorization header
